version: 2.1
orbs:
    node: circleci/node@3.0.1

jobs:
    build-and-test:
        docker:
            - image: cimg/node:12.16
        parallelism: 5     

        steps:

            - checkout
            - node/install-packages:
                pkg-manager: yarn      
            - run: mkdir ~/junit
            - run:
                name: Test application
                command: |
                    # TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
                    # yarn test $TEST
                  mkdir test-results
                  TEST_FILES=$(circleci tests glob "src/__tests__/*.js")
                  echo "$TEST_FILES" | circleci tests run --command="xargs yarn test -o junit_family=legacy --junitxml=test-results/junit.xml" --verbose --split-by=timings #--split-by=timings optional, only use if you are using CircleCI's test splitting
                    

                    
            - run:
                command: cp junit.xml ~/junit/
                when: always
            - store_test_results:
                path: ~/junit
            - store_artifacts:
                path: ~/junit

workflows:
    build-and-test:
      jobs:
        - build-and-test: 
              post-steps:
                - run:
                    command: echo "Hello world"
